name = "AtmosphericProfilesLibrary"
uuid = "86bc3604-9858-485a-bdbe-831ec50de11d"
authors = ["Climate Modeling Alliance"]
version = "0.1.7"

[deps]
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"

[compat]
Interpolations = "0.14, 0.15"
julia = "1"
